# Generated by Django 2.2.24 on 2021-11-09 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('student_key', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('enrollment', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
