# Generated by Django 2.2.24 on 2021-11-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='student_key',
            field=models.IntegerField(default=310165910),
        ),
    ]
